name: Translation statistics
# Pull statistics of translation in Transifex

on: 
  schedule:
    # runs tuesday at 6:00 UTC
    - cron: '0 6 * * 2'
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  ReportTranslationStats:

    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: github.repository_owner == 'qgis'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_branch: [release_3.28]
    env:
      TRANSIFEX_PASSWORD: ${{ secrets.TRANSIFEX_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Check out repository
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      with:
        fetch-depth: 1
        ref: ${{ matrix.target_branch }}

    - name: Set up Python 3.9
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python3 -m pip install requests

    - name: Report statistics
      run: python3 ./scripts/load_tx_stats.py $TRANSIFEX_PASSWORD

    - id: create_pr
      name: Create Pull Request for master
      uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5.0.0
      with:
        commit-message: Update statistics of translation
        title: Update statistics of translation
        delete-branch: true
        labels: Translation

    - name: Enable Pull Request Automerge
      run: gh pr merge --rebase --auto "${{ steps.create_pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ GH_TOKEN }}
